project:
  type: website
  output-dir: docs


website:
  title: "Minsong Kim's Project 1"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Data Viz
        menu: 
          - href: tidytue1.qmd
            text: Pokemon
          - href: tidytue2.qmd
            text: Wealth Inequality After Taxes
          - href: proj2.qmd
            text: Text Analysis of Obama's Tweets
          - href: proj3.qmd
            text: Monty Hall Simulation
          - href: proj4.qmd
            text: Ethical Dilemma in Data Science
          - href: proj5.qmd
            text: Exploring/Data Wrangling in SQL
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

